name: nps-demo
channels:
 - conda-forge
dependencies:
 - python=3.6
 - tiledb=1.2.2
 - jupyter
 - jupyterlab
 - numpy
 - pandas
 - pythreejs
 - ipyvolume
 - seaborn
 - ipyleaflet
 - ipywidgets
 - widgetsnbextension
 - pip:
   - git+https://git@github.com/TileDB-Inc/TileDB-Py.git@nps_demo
