name: nps-demo
channels:
 - conda-forge
dependencies:
 - python=3.6
 - tiledb
 - tiledb-py
 - jupyter
 - jupyterlab
 - numpy
 - pandas
 - pythreejs
 - ipyvolume
 - seaborn
 - ipyleaflet
 - ipywidgets
 - widgetsnbextension
